In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pymysql

MySQL connection to Python

In [9]:
sql_connection = pymysql.connect(
    host= "localhost",
    user= "root",
    password= "1234",
    database= "mydb"
)

In [10]:
query = """select * from orders"""
pd.read_sql(query,sql_connection)

C:\Users\LUKE\AppData\Local\Temp\ipykernel_22572\1469812412.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query,sql_connection)

,ï»¿OrderID,CustomerID,CustomerName,City,ProductID,ProductName,Category,OrderDate,Quantity,UnitPrice,Amount
0,1,101,Rahim,Dhaka,201,Laptop,Electronics,2025-01-03,3,"50,000","150,000"
1,2,102,Karim,Khulna,202,Mouse,Electronics,2025-01-05,3,"1,000","3,000"
2,3,103,Jamil,Dhaka,203,Keyboard,Electronics,2025-01-07,2,"1,500","3,000"
3,4,104,Salma,Chattogram,204,Printer,Electronics,2025-01-09,3,"15,000","45,000"
4,5,105,Nadia,Rajshahi,205,Monitor,Electronics,2025-01-11,3,"12,000","36,000"
...,...,...,...,...,...,...,...,...,...,...,...
95,96,106,Sohan,Sylhet,206,Router,Networking,2025-07-12,4,3000,12000
96,97,107,Tania,Dhaka,207,SSD,Storage,2025-07-14,1,6000,6000
97,98,108,Rifat,Khulna,208,HDD,Storage,2025-07-16,4,5000,20000
98,99,109,Imran,Barisal,209,UPS,Power,2025-07-18,5,8000,40000
99,100,110,Nila,Rangpur,210,Scanner,Electronics,2025-07-20,2,10000,20000

In [11]:
query = """select * from orders where city='Dhaka'"""
pd.read_sql(query,sql_connection)

C:\Users\LUKE\AppData\Local\Temp\ipykernel_22572\2100039899.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query,sql_connection)

,ï»¿OrderID,CustomerID,CustomerName,City,ProductID,ProductName,Category,OrderDate,Quantity,UnitPrice,Amount
0,3,103,Jamil,Dhaka,203,Keyboard,Electronics,2025-01-07,2,"1,500","3,000"
1,13,103,Jamil,Dhaka,203,Keyboard,Electronics,2025-01-27,2,"1,500","3,000"
2,23,103,Jamil,Dhaka,203,Keyboard,Electronics,2025-02-16,4,"1,500","6,000"
3,33,103,Jamil,Dhaka,203,Keyboard,Electronics,2025-03-08,5,"1,500","7,500"
4,43,103,Jamil,Dhaka,203,Keyboard,Electronics,2025-03-28,1,"1,500","1,500"
5,53,103,Jamil,Dhaka,203,Keyboard,Electronics,2025-04-17,4,1500,6000
6,63,103,Jamil,Dhaka,203,Keyboard,Electronics,2025-05-07,5,1500,7500
7,73,103,Jamil,Dhaka,203,Keyboard,Electronics,2025-05-27,1,1500,1500
8,83,103,Jamil,Dhaka,203,Keyboard,Electronics,2025-06-16,2,1500,3000
9,93,103,Jamil,Dhaka,203,Keyboard,Electronics,2025-07-06,3,1500,4500
10,1,101,Rahim,Dhaka,201,Laptop,Electronics,2025-01-03,3,"50,000","150,000"
11,11,101,Rahim,Dhaka,201,Laptop,Electronics,2025-01-23,4,"50,000","200,000"
12,21,101,Rahim,Dhaka,201,Laptop,Electronics,2025-02-12,2,"50,000","100,000"
13,31,101,Rahim,Dhaka,201,Laptop,Electronics,2025-03-04,3,"50,000","150,000"
14,41,101,Rahim,Dhaka,201,Laptop,Electronics,2025-03-24,4,"50,000","200,000"
15,51,101,Rahim,Dhaka,201,Laptop,Electronics,2025-04-13,5,50000,250000
16,61,101,Rahim,Dhaka,201,Laptop,Electronics,2025-05-03,1,50000,50000
17,71,101,Rahim,Dhaka,201,Laptop,Electronics,2025-05-23,2,50000,100000
18,81,101,Rahim,Dhaka,201,Laptop,Electronics,2025-06-12,4,50000,200000
19,91,101,Rahim,Dhaka,201,Laptop,Electronics,2025-07-02,4,50000,200000
20,7,107,Tania,Dhaka,207,SSD,Storage,2025-01-15,4,"6,000","24,000"
21,17,107,Tania,Dhaka,207,SSD,Storage,2025-02-04,1,"6,000","6,000"
22,27,107,Tania,Dhaka,207,SSD,Storage,2025-02-24,2,"6,000","12,000"
23,37,107,Tania,Dhaka,207,SSD,Storage,2025-03-16,3,"6,000","18,000"
24,47,107,Tania,Dhaka,207,SSD,Storage,2025-04-05,3,"6,000","18,000"
25,57,107,Tania,Dhaka,207,SSD,Storage,2025-04-25,1,6000,6000
26,67,107,Tania,Dhaka,207,SSD,Storage,2025-05-15,4,6000,24000
27,77,107,Tania,Dhaka,207,SSD,Storage,2025-06-04,1,6000,6000
28,87,107,Tania,Dhaka,207,SSD,Storage,2025-06-24,5,6000,30000
29,97,107,Tania,Dhaka,207,SSD,Storage,2025-07-14,1,6000,6000

In [12]:
query = """select * from orders where Amount>=50000"""
pd.read_sql(query,sql_connection)

C:\Users\LUKE\AppData\Local\Temp\ipykernel_22572\833935031.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query,sql_connection)

,ï»¿OrderID,CustomerID,CustomerName,City,ProductID,ProductName,Category,OrderDate,Quantity,UnitPrice,Amount
0,51,101,Rahim,Dhaka,201,Laptop,Electronics,2025-04-13,5,50000,250000
1,54,104,Salma,Chattogram,204,Printer,Electronics,2025-04-19,4,15000,60000
2,61,101,Rahim,Dhaka,201,Laptop,Electronics,2025-05-03,1,50000,50000
3,64,104,Salma,Chattogram,204,Printer,Electronics,2025-05-09,5,15000,75000
4,71,101,Rahim,Dhaka,201,Laptop,Electronics,2025-05-23,2,50000,100000
5,74,104,Salma,Chattogram,204,Printer,Electronics,2025-05-29,4,15000,60000
6,81,101,Rahim,Dhaka,201,Laptop,Electronics,2025-06-12,4,50000,200000
7,84,104,Salma,Chattogram,204,Printer,Electronics,2025-06-18,4,15000,60000
8,85,105,Nadia,Rajshahi,205,Monitor,Electronics,2025-06-20,5,12000,60000
9,91,101,Rahim,Dhaka,201,Laptop,Electronics,2025-07-02,4,50000,200000

In [16]:
query = """
select City,
sum(Amount) as Revenue
from orders
group by City
order by Revenue desc
"""
pd.read_sql(query,sql_connection)

C:\Users\LUKE\AppData\Local\Temp\ipykernel_22572\2095233756.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query,sql_connection)

         City   Revenue
0       Dhaka  895398.0
1  Chattogram  270255.0
2    Rajshahi  168216.0
3     Rangpur  130220.0
4     Barisal  120136.0
5      Khulna  111098.0
6      Sylhet   39039.0